.github/workflows/gradle.yml
build.gradle

Fixes package build. 
Check out the opensearch artifact and publish to local maven.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/b …

Modify opensearch version and fix buiild CI

---

.github/workflows/gradle.yml
build.gradle
release-notes/opensearch-performance-analyzer.release-notes-1.0.0.0-beta1.md

Build against opensearch 1.0.0-alpha2 …

Build against opensearch 1.0.0-beta1

---

.github/workflows/cd.yml
.github/workflows/gradle.yml
build.gradle
pa_bin/performance-analyzer-agent
src/main/resources/plugin-descriptor.properties

Update version from beta1 to rc1  …

Update version to rc1

---

.github/workflows/gradle.yml
src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigAction.java

https://github.com/opensearch-project/performance-analyzer/issues/20
Fix the actions performed by the legacy API. 
```
[root@e2eba3ca732e opensearch]# curl localhost:9200/_opendistro/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": true}'
{"currentPerformanceAnalyzerClusterState":1,"shardsPerCollection":0,"batchMetricsRetentionPeriodMinutes":7}[root@e2eba3ca732e opensearch]# 
[root@e2eba3ca732e opensearch]# 
[root@e2eba3ca732e opensearch]# curl -XGET http://localhost:9200/_opendistro/_performanceanalyzer/cluster/config …
```

Fix actions by legacy cluster endpoints

---

src/test/java/org/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandlerTests.java

Add tests to check for writer file creation only if metrics are present. …

Add tests to check for writer file only if metrics are present

---

.github/workflows/gradle.yml
release-notes/opensearch-performance-analyzer.release-notes-1.1.0.0.md

Switch opensearch from 1.x to 1.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/C …

Switch opensearch from 1.x to 1.1

---

.github/workflows/gradle.yml

Switch opensearch version from 1.x to 1.1 …

Switch opensearch version from 1.x to 1.1

---

build.gradle

Add checkstyle plugin reference

---

.github/workflows/gradle.yml
build.gradle
release-notes/opensearch-performance-analyzer.release-notes-1.2.0.0.md

1.2 release

---

release-notes/opensearch-performance-analyzer.release-notes-1.2.0.0.md

Add release notes for 1.2 release

---

.github/workflows/gradle.yml

Update the rca repo link

---

build.gradle
release-notes/opensearch-performance-analyzer.release-notes-1.2.3.0.md

Bump up log4j version to 2.17 and add release notes

---

release-notes/opensearch-performance-analyzer.release-notes-1.2.3.0.md

Add release notes for 1.2.3

---

.github/workflows/links.yml

Signed-off-by: dblock <dblock@dblock.org>
Fix and lock link checker at lycheeverse/lychee-action@v1.2.0.

Fix and lock link checker at lycheeverse/lychee-action@v1.2.0.

---

release-notes/opensearch-performance-analyzer.release-notes-1.2.4.0.md

Add release notes for 1.2.4

---

.github/workflows/gradle.yml
build.gradle

Signed-off-by: David Zane <davizane@amazon.com> …

Update branch refs "main" -> "1.3"

---

release-notes/opensearch-performance-analyzer.release-notes-1.3.0.0.md

Signed-off-by: David Zane <davizane@amazon.com> …

Adding 1.3 release notes

---

.github/workflows/gradle.yml
DEVELOPER_GUIDE.md
build.gradle
release-notes/opensearch-performance-analyzer.release-notes-1.3.0.0.md

Merge commits from main into 1.3 …

Merge commits from main into 1.3

---

.github/workflows/gradle.yml
build.gradle
src/main/resources/plugin-descriptor.properties

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Part of https://github.com/opensearch-project/opensearch-build/issues/1805

Bump version to 1.3.1

---

scripts/build.sh

We need to move build script file from opensearch-build package as suggested by build team. 
For more information on following Developer Certificate of Origin and signing off your commits, …

Moving build script file here from opensearch build package

---

.github/workflows/gradle.yml
build.gradle

Changes for 2.0. Had Cut a branch from main for PA and RCA today. This change makes PA 2.0 version point to RCA 2.0.
https://github.com/opensearch-project/performance-analyzer/issues/141 …

Changes to point to RCA 2.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.0.0.0-rc1.md

Adding release notes to 2.0 branch from main. …

Adding release notes for 2.0.0-rc1 (#193)

---

release-notes/opensearch-performance-analyzer.release-notes-2.0.0.0-rc1.md

Removing Deprecation section. Added documentation section instead. …

Updating release notes for 2.0.0-rc1

---

release-notes/opensearch-performance-analyzer.release-notes-2.0.0.0-rc1.md

Updating release notes for 2.0.0-rc1.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-cert …

Update release notes

---

packaging/performance-analyzer-agent-cli

Add env var check during installation …

Add env var check during installation

---

src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java

Signed-off-by: Ankit Jain <jain.ankitk@gmail.com>

Fixing header key value issue (#203)

---

build.gradle
src/main/resources/plugin-descriptor.properties

https://github.com/opensearch-project/performance-analyzer/issues/210 …

Removing rc1 qualifier

---

build.gradle
src/main/resources/plugin-descriptor.properties

https://github.com/opensearch-project/performance-analyzer/issues/210
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/mai …

Removing rc1 qualifier (#217)

---

src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
src/test/java/org/opensearch/performanceanalyzer/ITConfig.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/CpuMetricsIT.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/HeapMetricsIT.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/PageFaultMetricsIT.java

Backport/backport 204/208 to 2.0

---

src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
src/test/java/org/opensearch/performanceanalyzer/ITConfig.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/CpuMetricsIT.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/HeapMetricsIT.java
src/test/java/org/opensearch/performanceanalyzer/integ_test/PageFaultMetricsIT.java

#203 #204 #208 
- [] New functionality has been documented.
- [] New functionality has javadoc added

Backport/backport 204/208 to 1.3

---

release-notes/opensearch-performance-analyzer.release-notes-2.0.0.0.md

Add release notes for 2.0 GA

---

.github/workflows/gradle.yml
build.gradle
src/main/resources/plugin-descriptor.properties

https://github.com/opensearch-project/opensearch-build/issues/2101
N/A
N/A

Version Increment to 1.3.3 OpenSearch release

---

build.gradle
src/main/resources/plugin-descriptor.properties

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 2.0.1
Part of https://github.com/opensearch-project/opensearch-build/issues/2165
For more information on following Developer Certificate of Origin and signing off your commits, …

Incremented version to 2.0.1

---

release-notes/opensearch-performance-analyzer.release-notes-2.1.0.0.md

Add release notes for 2.1 release …

Add release notes for 2.1 release

---

build.gradle
release-notes/opensearch-performance-analyzer.release-notes-2.2.0.0.md

Signed-off-by: Sagar Upadhyaya <sagar.upadhyaya.121@amazon.com>
Pointing RCA to 2.2  …

Updating RCA branch to 2.2

---

scripts/build.sh

Signed-off-by: prudhvigodithi <pgodithi@amazon.com>
Default build.sh in build repo for 1.3.x includes task publishPluginZipPublicationToZipStagingRepository.
Additional context
https://github.com/opensearch-project/opensearch-build/issues/2470
N/A
N/A
N/A
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certifi …

Add build.sh

---

release-notes/opensearch-performance-analyzer.release-notes-2.3.0.md

Signed-off-by: Kaushal Kumar <kshkmr@amazon.com>
Add release-notes for 2.3 release. …

add release notes

---

build.gradle

Update bwc tests from 2.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer …

Update bwc tests from 2.1

---

src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerRCAHealthCheckIT.java

Signed-off-by: Kiran Prakash <awskiran@amazon.com>
Ankit's [change](https://github.com/opensearch-project/performance-analyzer/pull/225/files) was never backported to 1.3 which is failing IT tests in RCA package. 
I believe this will fix it, if not I will revert it asap.

Backport API path in IntegrationTest to 1.3

---

release-notes/opensearch-performance-analyzer.release-notes-2.4.0.md

Signed-off-by: David Zane <davizane@amazon.com> …

Add release notes for 2.4 release

---

release-notes/opensearch-performance-analyzer.release-notes-2.4.0.md

Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Fix the heading for the release notes …

Update the correct version for the release notes

---

release-notes/opensearch-performance-analyzer.release-notes-2.5.0.0.md

Signed-off-by: Kiran Prakash <awskiran@amazon.com>
Adding Release Notes - 2.5.0

Release Notes - 2.5.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.5.0.0.md

Signed-off-by: Kiran Prakash <awskiran@amazon.com>
Adding Release Notes - 2.5.0

[Backport] Release Notes - 2.5.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.5.0.0.md
release-notes/opensearch-performance-analyzer.release-notes-2.6.0.0.md

- Adding release notes  for 2.6 - https://github.com/opensearch-project/performance-analyzer/issues/384
- Added missing release notes for 2.5 version …

Adding 2.6 release notes

---

build.gradle

Fix for failing OS 1.3.9 release build

Upgrade jackson to 2.14.2

---

build.gradle

Fixes https://github.com/opensearch-project/performance-analyzer/issues/332
Same as Security plugin fix https://github.com/opensearch-project/security/pull/2275

Pin bcel version

---

release-notes/opensearch-performance-analyzer.release-notes-2.7.0.0.md

Adding release notes for 2.7.0
[A clear and concise description of what you want to happen.](https://github.com/opensearch-project/performance-analyzer/issues/415) …

Adding release notes for 2.7.0

---

build.gradle

Make dependencies match ones from core.

---

build.gradle

https://github.com/opensearch-project/performance-analyzer-commons/issues/2
Fix SHA update for PA-Commons repo in build.gradle
```
> Task :dependencyLicenses
Adding sha for performance-analyzer-commons-1.0.0-SNAPSHOT.jar
```

Fix SHA update for PA-Commons repo in build.gradle

---

release-notes/opensearch-performance-analyzer.release-notes-2.8.0.0.md

Adding release notes for 2.8.0

---

.github/workflows/cd.yml
.github/workflows/gradle.yml
bin/performance-analyzer-agent
build.gradle

Updating the build.gradle and Install for the release

[2.8] Updating the build.gradle and Install for the release

---

build.gradle

upgrade Spotbugs version for CVE-2022-45688

upgrade Spotbugs version for CVE-2022-45688

---

src/main/java/org/opensearch/performanceanalyzer/collectors/ShardStateCollector.java

Change is incoming from upstream core.
- [] All tests pass

Fix `routingTable`

---

.github/workflows/cd.yml
.github/workflows/gradle.yml
build.gradle

https://github.com/opensearch-project/performance-analyzer/issues/488
Add changes for 2.9 branch

Add changes for 2.9 branch

---

bin/performance-analyzer-agent
build.gradle

https://github.com/opensearch-project/performance-analyzer/issues/488
Update performance-analyzer-agent script for OS 2.9

Update performance-analyzer-agent script for OS 2.9

---

release-notes/opensearch-performance-analyzer.release-notes-2.9.0.0.md

Add release notes for PA and RCA 2.9.0 release
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#devel …

Adding release notes for 2.9.0

---

build.gradle

Update BWC version to 2.9(N-1) for v2.10 release

Update BWC version to 2.9

---

build.gradle

update performance-analyzer-commons version

update performance-analyzer-commons version

---

release-notes/opensearch-performance-analyzer.release-notes-2.10.0.0.md

https://github.com/opensearch-project/performance-analyzer/issues/524
Add Release Notes for v2.10.0

Add Release Notes for v2.10.0

---

.github/workflows/cd.yml
.github/workflows/gradle.yml
build.gradle

[https://github.com/opensearch-project/performance-analyzer/issues/547](https://github.com/opensearch-project/performance-analyzer/issues/547) 
Add changes for 2.11 branch

Add changes for 2.11 branch

---

build.gradle

Update BWC version for v2.11

---

build.gradle

Update BWC version for 2.10
- [] Backport Labels added.
- [] New functionality includes testing.

Update BWC version for 2.10

---

release-notes/opensearch-performance-analyzer.release-notes-2.10.0.0.md
release-notes/opensearch-performance-analyzer.release-notes-2.11.0.0.md

Add Release Notes for v2.11.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.11.0.0.md

Fix typo in release notes

---

.gitignore

QoL: add bin to gitignore

---

build.gradle

Update performance-analyzer-commons to use the tag 1.2.0
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTIN …

Upgrade pa-commons version to 1.2.0

---

.github/CODEOWNERS
MAINTAINERS.md
build.gradle

1. Add new Contributors to the repo
2. Bump Commons library version

Add new maintainers to repo

---

build.gradle

bumped up the BWC version to 2.11
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certific …

bump up the BWC version to 2.11

---

release-notes/opensearch-performance-analyzer.release-notes-2.12.0.0.md

Add release notes for 2.12 release
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certifi …

Add Release Notes for v2.12.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.13.0.0.md

Adding release notes for 2.13.0
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificat …

Add Release Notes for v2.13.0

---

.github/workflows/cd.yml
.github/workflows/gradle.yml
build.gradle
src/main/resources/plugin-descriptor.properties

Added the version changes for 2.13 branch as these were missed during 2.13 branch cut.

Add changes for 2.13 release

---

release-notes/opensearch-performance-analyzer.release-notes-1.3.16.0.md

Add release notes for 1.3.16
Part of https://github.com/opensearch-project/opensearch-build/issues/4531

Add release notes for 1.3.16

---

build.gradle

https://github.com/opensearch-project/performance-analyzer/issues/663#issuecomment-2161311887 …

Bump PA to use 1.4.0 PA commons lib

---

release-notes/release-notes/opensearch-performance-analyzer.release-notes-2.15.0.0.md

Add release notes for v2.15.0
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate- …

Create opensearch-performance-analyzer.release-notes-2.15.0.0.md (#1)

---

build.gradle

Bumping bouncycastle to v1.78. 
Resolves https://github.com/advisories/GHSA-m44j-cfrm-g8qc, https://github.com/advisories/GHSA-v435-xc8x-wvr9 and https://github.com/advisories/GHSA-8xfc-gm6g-vgpv. …

Bumping bouncycastle to v1.78

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollector.java
src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java
src/main/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListener.java
src/main/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListener.java
src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannel.java
src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportInterceptor.java
src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandler.java
src/main/java/org/opensearch/performanceanalyzer/util/Utils.java
src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java
src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollectorTests.java
src/test/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListenerTests.java
src/test/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListenerTests.java
src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannelTests.java
src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandlerTests.java
src/test/java/org/opensearch/performanceanalyzer/util/UtilsTests.java

porting the change https://github.com/opensearch-project/performance-analyzer/pull/688 from the 2.x.
For more information on following Developer Certificate of …

Port pr 688

---

build.gradle

Bump PA commons to 1.5.0 for release 2.16 …

Bump PA commons to 1.5.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.16.0.0.md

Adds release notes for 2.16.0

---

src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java

fixes the cacheConfigRTFCollector UT
NA

fixes the cacheConfigRTFCollector UT

---

build.gradle

bump up PA commons to 1.6

---

src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java

[backport 2.x]fixes the cacheConfigRTFCollector UT (#713)

---

build.gradle

[Backport 2.17] Increment version to 2.17.0-SNAPSHOT (#704)

---

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollector.java
src/main/java/org/opensearch/performanceanalyzer/util/Utils.java
src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java

(cherry picked from commit 2624469183e77c701b55fe0f36f740bb766f8e58)

[Backport 2.17] Added cacheConfig Collector (#690) (#710)

---

build.gradle

(cherry picked from commit 5a2ac55dd4a67b3635f407bf0614684988bf5aca)

[Backport 2.17] bump up PA commons to 1.6 (#712) (#716)

---

src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java
src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java
src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigActionTests.java
src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigActionTests.java

(cherry picked from commit e25c559eb866dcb3cca97d3a2459e435cf04b27f)

[Backport 2.17] fixes the UT failures caused due to Identity Service (#714) (#715)

---

src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java

[Backport 2.17] fixes the cacheConfigRTFCollector UT (#713) (#717)

---

release-notes/opensearch-performance-analyzer.release-notes-2.17.0.0.md

Release notes for release - 2.17.0

Adds release notes for 2.17.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.17.0.0.md

(cherry picked from commit dc57bb4c62348abfc6d043e0ea20a8947a108029)

Adds release notes for 2.17.0 (#725) (#726)

---

.github/workflows/gradle.yml

fixes the docker build issue.
- [] New functionality includes testing.

Fixes failing docker issue

---

release-notes/opensearch-performance-analyzer.release-notes-2.18.0.0.md

Empty release notes for 2.18.0.

Adds release notes for 2.18.0

---

release-notes/opensearch-performance-analyzer.release-notes-2.18.0.0.md

backport of https://github.com/opensearch-project/performance-analyzer/pull/753

release notes 2.18

---

.github/workflows/gradle.yml

Add v1 docker-compose installation for 1.3 branch
https://github.com/opensearch-project/opensearch-build/issues/4990

Add v1 docker-compose installation for 1.3 branch

---

licenses/listenablefuture-LICENSE.txt
release-notes/opensearch-performance-analyzer.release-notes-1.3.20.0.md
src/main/java/org/opensearch/performanceanalyzer/collectors/NodeStatsAllShardsMetricsCollector.java

Adds release notes for 1.3.20 release. It also address a few test cases failing due to jackson version upgrade in the OpenSearch core.

Adds release notes - 1.3.20

---

licenses/listenablefuture-LICENSE.txt

Adds Missing listenablefuture licenses

Missing listenablefuture licenses

---

release-notes/opensearch-performance-analyzer.release-notes-2.19.0.0.md

Adds release notes for 1.3.20 release. 

Adds release notes - 2.19.0

---

.github/workflows/gradle.yml

bump codecov/codecov-action@v3 -> codecov/codecov-action@v5
bump actions/upload-artifact@v3 -> actions/upload-artifact@v4

bump github actions version

---

build.gradle

Fix for CVE-2025-27820

---

build.gradle

Upgrades the commons-lang3 version
