opensearch-project/performance-analyzer

release-notes/opendistro-for-elasticsearch-performance-analyzer.release-notes-1.13.0.0.md, release-notes/opensearch-performance-analyzer.release-notes-1.0.0.0-beta1.md, src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java
Update plugin name and add release notes for beta release.
Integration testing passing in local. 
```
> Task :integTest
com.amazon.opendistro.opensearch.performanceanalyzer.integ_test.HeapMetricsIT > checkHeapInit STANDARD_OUT
[2021-04-26T23:01:45,414][INFO ][c.a.o.o.p.i.HeapMetricsIT] [checkHeapInit] before test
[2021-04-26T23:01:45,698][INFO ][c.a.o.o.p.i.HeapMetricsIT] …
```
=> Update plugin name and add release notes

src/main/java/com/amazon/opendistro/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java
Signoff by: Harold Xiao haoruxia@amazon.com
When running PA unit tests, errors with NoSuchFile exceptions will pop out, the reason is that the path to store the conf files is not exist. This PR add a conditional check to add the directory to avoid the exceptions. 
Prerequisite: Add CONFIG_DIR_NOT_FOUND in StatExceptionCode 
(https://github.com/opensearch-project/performance-analyzer-rca/pull/11/files)
For …
=> Create conf directory if not exist to avoid NoSuchFile exceptions

build.gradle
Upgrade Jackson version to 2.11.4 to match OpenSearch core.
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-28491
The older version of Jackson was flagged in the linked CVE.
Upgrade to a later version not affect by the CVE. The version 2.11.4 is chosen to match OpenSearch core.
We could upgrade to a later version of Jackson, but I think it makes sense to match OpenSearch core to avoid any compatibility bugs. Note that the CVE does not apply to versions 2.11.4 and later.
For more …
=> Upgrade Jackson version to 2.11.4

src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigAction.java, src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigAction.java, src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigAction.java, src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java, src/main/java/org/opensearch/performanceanalyzer/http_action/config/RestConfig.java, src/test/java/org/opensearch/performanceanalyzer/ConfigOverridesIT.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerIntegTestBase.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerRCAHealthCheckIT.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProviderTests.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/CpuMetricsIT.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/HeapMetricsIT.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/PageFaultMetricsIT.java
Plugin resources will appear under `/_plugins` instead of `/_opendistro`.
Following the [upgrade guide](https://github.com/opensearch-project/opensearch-plugins/blob/main/UPGRADING.md#rest-apis-backward-compatibility) to rename our REST resources.
=> Update REST resources to follow new OpenSearch naming convention

README.md
Update the README to replace the legace `/_opendistro` REST resource with `/_plugins`.
=> Update rest endpoint names in README

src/test/java/org/opensearch/performanceanalyzer/ConfigOverridesIT.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerRCAHealthCheckIT.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/CpuMetricsIT.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/HeapMetricsIT.java, src/test/java/org/opensearch/performanceanalyzer/integ_test/PageFaultMetricsIT.java
In order to validate backward compatibility, we want our integration tests to exercise the legacy `/_opendistro` endpoint in addition to the `/_plugins` endpoint.
Updating integration tests to run the same tests against both `/_opendistro` and `/_plugins`.
=> Add legacy REST endpoints to integration tests

build.gradle
1. Re-enabled the 'licenseHeaders' check in the build.gradle file.
Related to - opensearch-project/opensearch-plugins#49
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).
Signed-off-by: Ketan Verma <vermketa@amazon.com>
=> Enabled automated license header checks

src/main/java/org/opensearch/performanceanalyzer/writer/EventLogQueueProcessor.java
https://github.com/opensearch-project/performance-analyzer/issues/30
We write to tmp files first before renaming to actual epoch file. 
Append/ Create to the tmp file only if we have metrics to publish.
For more information on following Developer Certificate …
=> Create writer file if metrics are available

src/main/java/org/opensearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java, src/test/java/org/opensearch/performanceanalyzer/collectors/ShardIndexingPressureMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerControllerTests.java
**Description**
Use Collector override disable list for `ShardIndexingPressureMetricCollector`. With this change `ShardIndexingPressureMetricCollector` will be enabled by default with the controls to disable it dynamically
=> Use Collector override disable list for ShardIndexingPressureMetricCollector

README.md, build.gradle, src/main/java/org/opensearch/performanceanalyzer/writer/EventLogQueueProcessor.java
1. Addresses Joydeep's comment on [PR-36](https://github.com/opensearch-project/performance-analyzer/pull/36). Moved deleteAllFiles() to inside scheduleExecutor(), this ensures that deleteAllFiles() is invoked once and before beginning of event log file generation. 
2. Minor change around fixing the official documentation to resolve Link Checker errors.
By …
=> Handling purging of lingering files before scheduleExecutor start.

src/main/java/org/opensearch/performanceanalyzer/writer/EventLogQueueProcessor.java
https://github.com/opensearch-project/performance-analyzer/issues/39
Fix failing event file handler test. Formatting changes was brought in by spotless.
For more information on following Developer …
=> Fix failing file handler test

README.md
Fixes typo in apis to enable PA batch metrics API in README.md
There is a typo in the apis to enable batch metrics for cluster and node.
Typo fix
=> Fixes typo in APIs to enable PA batch metrics API in readme

src/main/java/org/opensearch/performanceanalyzer/collectors/MasterServiceEventMetrics.java, src/main/java/org/opensearch/performanceanalyzer/collectors/NodeStatsAllShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/NodeStatsFixedShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java, src/main/java/org/opensearch/performanceanalyzer/config/setting/ClusterSettingsManager.java, src/main/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListener.java, src/main/java/org/opensearch/performanceanalyzer/transport/PerformanceAnalyzerTransportRequestHandler.java, src/test/java/org/opensearch/performanceanalyzer/collectors/StatsTests.java
StatsCollector is used by RCA-Agent and PerformanceAnalyzer Plugin to publish service metrics. We run this collector through ScheduledMetricCollectorsExecutor and the executor can mark the collector as SLOW and subsequently MUTED if the collector is slow. A muted collector doesn't emit any metrics and thus we can end up missing the helpful service metrics.
This PR contains changes to skip muting for StatsCollector and re-factoring to move away from StatExceptionCode to Metric Aggregators.
This is an extension of this PR https://github.com/opensearch-project/performance-analyzer-rca/pull/37.
A …
=> Refactor stats collector

build.gradle
Signed-off-by: Marc Handalian <handalm@amazon.com>
This change removes the main branch as a dependency when running spotless.
The spotless check will not compare for changes against main and will check every file when building a branch.
closes #44 
- [ x] Commits are signed per the DCO using --signoff
=> Remove dependency on main branch when running spotless.

.github/workflows/cd.yml, .github/workflows/gradle.yml, build.gradle
https://github.com/opensearch-project/performance-analyzer/issues/45
Introduced two different env variables that will be used for building RCA package (which runs as a part of PA build). 
```cloneRcaProject``` -> this is used to clone the ```main``` branch of the RCA package. If set true, it clones RCA package into ```../performance-analyzer-rca``` location . By default it is set to false in that case it checks the same location for this package, if it exists the test continues. If not, the test fails. 
```rcaProjectDir``` -> this is used to specify the location where the rca package is checked …
=> Updates to gradle build file

build.gradle
Signed-off-by: Marc Handalian <handalm@amazon.com>
The build is failing when opensearch version specified is not the same as the default value.
The cause of this problem is updateShas is invoked, which is a task in this project, during the doLast step of the buildRCA task.  This task is not invoked with any properties passed in during the initial build command.
This change will execute this directly with finalizedBy instead of using doLast and executing from the command line.
passing the version string down to doLast.  I would rather directly invoke the task without executing from shell.
closes #51 
- [ …
=> Fix build to succeed with opensearch_version provided

.github/workflows/gradle.yml, build.gradle
Signed-off-by: dblock <dblock@amazon.com>
- Fix snapshot build.
- Use OpenSearch 1.1 by default.
There's a circular dependency described in #50, so https://github.com/opensearch-project/performance-analyzer-rca/pull/55 is needed. Once this is merged I'll switch references to my fork that contains this code.
=> Fix snapshot build using OpenSearch 1.1.

.github/workflows/gradle.yml
Signed-off-by: dblock <dblock@amazon.com>
Now that https://github.com/opensearch-project/performance-analyzer-rca/pull/55 has been merged, use its main branch.
Together with #53, closes #43.
=> Use performance-analyzer-rca main branch.

src/main/java/org/opensearch/performanceanalyzer/writer/EventLogQueueProcessor.java
https://github.com/opensearch-project/performance-analyzer/issues/61
Writer metrics are filling up the disk. Currently, the cleanup method deletes the writer files (https://github.com/opensearch-project/performance-analyzer/blob/main/src/main/java/org/opensearch/performanceanalyzer/writer/EventLogQueueProcessor.java#L190)
This method deletes files up to the current time, but the file creation happens after this. Thus one file is left out during the file deletion. This cause accumulation of writer files.
Delete writer files only when they are older than 60sec.
Add any other …
=> Fix deleting files within 60sec interval

build.gradle
https://github.com/opensearch-project/performance-analyzer/issues/81
Remove packaging deb and rpm related files in tar artifacts. 
From opendistro 1.10.1 release the upgrade on deb and rpm is broken. Need to revisit postinst and postrm scripts. As a part of this effort if the deb and rpm files are needed in the install directory, an env variable can be used to filter out the unnecessary files. 
https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/235
A clear and concise description of any alternative solutions or features you've …
=> Fix deb, rpm build and remove deb, rpm related files from tar artifacts

.github/workflows/gradle.yml, build.gradle
=> Change main to 1.2

packaging/deb/postinst, packaging/rpm/postinst
#82 
`/plugins/opensearch-performance-analyzer/performance-analyzer-rca/` is not required and used only for copying `performance-analyzer-rca` to OS home dir. Hence, we can move `performance-analyzer-rca` to OS home dir instead of copying it to remove duplicate files.
`plugins/opensearch-performance-analyzer` before moving `performance-analyzer-rca`
```
du -hs plugins/opensearch-performance-analyzer
69M	plugins/opensearch-performance-analyzer
```
`plugins/opensearch-performance-analyzer` after moving `performance-analyzer-rca`
```
du -hs plugins/opensearch-performance-analyzer
34M …
```
=> mv instead of cp performance-analyzer-rca to OS home dir

.github/workflows/gradle.yml, release-notes/opensearch-performance-analyzer.release-notes-1.2.1.0.md
Update branch to 1.2 and add release notes …
=> Update branch to 1.2 and add release notes

.github/workflows/gradle.yml, build.gradle, src/main/resources/plugin-descriptor.properties
#114 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUT …
=> Upgrade plugin version to 1.2.4 and log4j to 2.17.1

packaging/performance-analyzer-agent-cli
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
The `InitialBootClassLoaderMetaspaceSize` JVM command line flag has been deprecated in JDK-15 [1] and removed in JDK-16 [2]. 
[1] https://bugs.openjdk.java.net/browse/JDK-8242426 
[2] https://bugs.openjdk.java.net/browse/JDK-8221173
Related to https://github.com/opensearch-project/opensearch-build/issues/1523
Drop `InitialBootClassLoaderMetaspaceSize` usage
Make the command line logic dependent on JVM version being used
Closes https://github.com/opensearch-project/performance-analyzer/issues/125
By submitting this pull request, I …
=> Removing deprecated InitialBootClassLoaderMetaspaceSize JVM command line flag

packaging/performance-analyzer-agent-cli
The agent CLI starts opensearch-cli in a child process. This has some
nasty drawbacks:
- any signal passed to the agent is not forwarded to opensearch-cli,
which forces one to kill the process group to actually kill the PA,
- the exit code of the agent is always 0, and the actual exit code of
opensearch-cli is lost
This commit execs the opensearch-cli command instead of running it in a
subprocess, so that any signal is forwarded to the callee, and any exit
code is forwarded to the caller.
See https://github.com/opensearch-project/opensearch-build/issues/1487
=> fix: don't run opensearch-cli in a child process

pa_bin/performance-analyzer-agent
Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
Closes https://github.com/opensearch-project/performance-analyzer/issues/132
Add support for OPENSEARCH_JAVA_HOME (see please https://github.com/opensearch-project/OpenSearch/issues/1872), as an alternative to JAVA_HOME (both should work just fine).
N/A
See please https://github.com/opensearch-project/OpenSearch/issues/1872
For more information on following Developer Certificate of Origin and signing off your commits, …
=>  [FEATURE] Add support for OPENSEARCH_JAVA_HOME

build.gradle
Signed-off-by: Sagar Upadhyaya <upasagar@amazon.com>
While building PA along with RCA and running unit tests https://github.com/opensearch-project/performance-analyzer-rca/pull/145 for jdk8, workflow step failed as we have a logic currently in build.gradle to export a module which is not supported for versions <=8.
Adding the desired check.
By submitting this pull request, I confirm that my contribution is made under the …
=> Adding check to avoid adding module export for jdk8

.github/workflows/gradle.yml, DEVELOPER_GUIDE.md, build.gradle
1. Adding CI matrix for JDK 8, 11 and 14 in CI workflow
2. Updating developer guide to use JDK 11
Solves: https://github.com/opensearch-project/performance-analyzer/issues/91
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-cer …
=> Adding CI matrix for jdk 8, 11 and 14

src/test/java/org/opensearch/performanceanalyzer/reader_writer_shared/EventLogFileHandlerTests.java
Fix EventLogFileHandlerTests flaky test
Deleting all the event log files before starting
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyz …
=> Fix EventLogFileHandlerTests flaky test

.github/workflows/gradle.yml, build.gradle, src/main/resources/plugin-descriptor.properties
Signed-off-by: Sayali Rohidas Gaikawad <gaiksaya@amazon.com>
Coming from https://github.com/opensearch-project/opensearch-build/issues/1805 post release activity.
=> Incremented version to 1.3.2.

build.gradle, licenses/paranamer-LICENSE.txt
https://github.com/opensearch-project/performance-analyzer/issues/164 …
=> Enable dependency license check and removing unused license

build.gradle, src/main/resources/plugin-descriptor.properties
Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.
=> Change 2.0-alpha1 to 2.0-rc1.

pa_config/opensearch_security.policy
Signed-off-by: Surya Sashank Nistala <snistala@amazon.com>
Adds management permission (control) in security policy file to enable/disable thread contention monitoring
=> Adds management permission (control) in security policy file

release-notes/opensearch-performance-analyzer.release-notes-2.0.0.0-rc1.md
Adding release notes for 2.0.0.0-rc1. https://github.com/opensearch-project/performance-analyzer/issues/141
For more information on following Developer Certificate of Origin and signing off …
=> Adding release notes for 2.0.0-rc1

packaging/performance-analyzer-agent-cli
Add env var check during installation …
=> Add env var check during installation

build.gradle, scripts/build.sh
Signed-off-by: Sagar Upadhyaya <sagar.upadhyaya.121@amazon.com>
https://github.com/opensearch-project/performance-analyzer/issues/202
```
Testing - Verified by running publishPluginZipPublicationToZipStagingRepository task that zip is being generated in local maven repo.
```
For more information on following Developer …
=> Adding custom plugin to publish zips to local repo

build.gradle, scripts/build.sh
Co-authored-by: Sagar Upadhyaya <sagar.upadhyaya.121@gmail.com>
Backporting  - https://github.com/opensearch-project/performance-analyzer/pull/229 into 2.0
For more information on following …
=> [Backport] Adding custom plugin to publish zips to local repo 

.github/workflows/gradle.yml, build.gradle, src/main/resources/plugin-descriptor.properties
Signed-off-by: Zelin Hao <zelinhao@amazon.com>
Incremented version to 1.3.4.
Part of https://github.com/opensearch-project/opensearch-build/issues/2205
For more information on following Developer Certificate of Origin and signing off your commits, …
=> Incremented version to 1.3.4.

README.md
Signed-off-by: cwillum <cwmmoore@amazon.com>
**Is your feature request related to a problem?**
This fixes the issue for the Performance Analyzer plugin in [#921](https://github.com/opensearch-project/documentation-website/issues/921).
Replaced the link to the Forum discussion in the README.md file so that it points to the OpenSearch forum rather than the defunct Open Distro forum.
=> Replace Forum link in Performance Analyzer plugin README.md

build.gradle
Fix failing bwc tests
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blo …
=> Fix failing bwc tests

src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerResourceProvider.java
We saw an issue where threads were stuck indefinitely while waiting for metric response. This happened as PA plugin creates connection and request metrics from PA agent on port 9600. PA agent somehow resulted in exception and didn't send the response back making PA wait forever.
**Repro**
Threw exception in RCA deliberately [here](https://github.com/opensearch-project/performance-analyzer-rca/blob/main/src/main/java/org/opensearch/performanceanalyzer/rest/QueryMetricsRequestHandler.java#L315-L316).
By issuing command like ```GET /_performanceanalyzer/_agent/metrics``` on 9200, it got stuck. And issuing multiple such caused …
=> Adding connection read timeout to prevent indefinite wait

.github/CODEOWNERS, CODEOWNERS, MAINTAINERS.md
Fixes https://github.com/opensearch-project/performance-analyzer/issues/382
=> Baseline MAINTAINERS, CODEOWNERS

.github/workflows/maven-publish.yml, build.gradle
https://github.com/opensearch-project/performance-analyzer/issues/385
Testing
```
./gradlew publishPluginZipPublicationToSnapshotsRepository
```
```
find snapshots | sort
snapshots
snapshots/org
snapshots/org/opensearch
snapshots/org/opensearch/plugin
snapshots/org/opensearch/plugin/performance-analyzer
snapshots/org/opensearch/plugin/performance-analyzer/3.0.0.0-SNAPSHOT
snapshots/org/opensearch/plugin/performance-analyzer/3.0.0.0-S …
```
=> Publish snapshot to maven

src/main/java/org/opensearch/performanceanalyzer/collectors/AdmissionControlMetricsCollector.java
PA AdmissionControl colector is taking dependency on AOS's AdmissionControl plugin to retrieve JVMMP & Request_Size 
quota related metrics. PA uses reflection to retrieve static insances of AdmissionControllers. 
Unit now it worked fine since, Jetty plugin was in /lib diretory and was getting loaded by same classloader. But now that AOS is moving to Netty, Netty is completely seperate plugin and no in /lib folder. Hence PA & Netty plugins shares different classloaders. However, there is a way we can still load AdmissionControl classes with parent ClassLoaders. PluginService when loads extended plugins, it passes parent classloader for all extended plugins. …
=> Fix AdmissionControl class loading issue in Netty/PA communication

src/main/java/org/opensearch/performanceanalyzer/collectors/AdmissionControlMetricsCollector.java
This reverts commit 7c9a49321e62f884bc7621b677ca31c7eb7b35aa, breaking the main.
```
org.opensearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin class [org.opensearch.performanceanalyzer.PerformanceAnalyzerPlugin]
»  	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:184) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:171) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) ~[opensearch-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) ~[opensearch-cli-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
»  	at …
```
=> Revert "Fix AdmissionControl class loading issue in Netty/PA communication (#402)"

build.gradle
Make junit, jackson, log4j and netty dependencies match ones from core.
For more information on following Developer Certificate of Origin and signing off …
=> Make dependencies match ones from core.

build.gradle
Matching the netty version with the one core build-tools lib.
For more information on following Developer Certificate of Origin and signing off your …
=> Make netty version match the one from core.

build.gradle
(cherry picked from commit 7efb6e1c3680dbd96beb54b4538bb572295af16b)
For more information on …
=> [Backport 2.x] Make dependencies match ones from core. (#417)

src/main/java/org/opensearch/performanceanalyzer/collectors/CircuitBreakerCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java
PR to adjust to changes in https://github.com/opensearch-project/performance-analyzer-rca/pull/323.
For more information on following Developer Certificate of Origin and signing off your …
=> Add collector update Stat calls

.github/workflows/cd.yml, .github/workflows/gradle.yml, bin/performance-analyzer-agent, build.gradle
Updating the build.gradle and Install for the release
https://github.com/opensearch-project/performance-analyzer/issues/415
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONT …
=> [2.7] Updating the build.gradle and Install for the release

src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigActionTests.java
Due to https://github.com/opensearch-project/OpenSearch/pull/7246, added dummy `IdentityService` objects into `ResController` constructors used in tests.
=> Update RestController constructor for tests.

src/main/java/org/opensearch/performanceanalyzer/collectors/ShardStateCollector.java
Revert the routingTable.indicesRouting.keySet change for 2.8 release since the necessary OpenSearch side changes are not in yet.
=> revert the routingTable.indicesRouting.keySet change

src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetrics.java, src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java, src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerThrottlingMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/NodeDetailsCollector.java, src/test/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetricsTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetricsTests.java, src/test/java/org/opensearch/performanceanalyzer/hwnet/CollectMetricsTests.java
All usages have been replaced with the "cluster manager" variants.
I'm looking at removing MasterService in the core repo and this appears to be the only remaining reference outside of core. Note the build appears to be broken on main (?) but this commit can be cleanly cherry picked on to the 2.x branch where it will compile successfully.
Here is the closed issue that refers to removing deprecated APIs: #152
=> Remove usage of deprecated "master" APIs

build.gradle, src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java, src/main/java/org/opensearch/performanceanalyzer/collectors/NodeStatsAllShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/NodeStatsFixedShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/util/Utils.java, src/test/java/org/opensearch/performanceanalyzer/collectors/JsonKeyTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/NodeStatsFixedShardsMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/ThreadPoolMetricsCollectorTests.java
`NodeStatsAllShardsMetricsCollector` is already released, redundant to run `NodeStatsFixedShardsMetricsCollector`. The Collector can further be removed in the future revision.
=> Depreceate NodeStatsFixedShardsMetricsCollector in favor of NodeStatsAllShardsMetricsCollector

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java
Fixing the breaking change - https://github.com/opensearch-project/performance-analyzer/issues/555
Resolves - https://github.com/opensearch-project/performance-analyzer/issues/555
For more information on following Developer Certificate of Origin and …
=> Add tracer to getTransports

src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceEventMetrics.java, src/main/java/org/opensearch/performanceanalyzer/collectors/ClusterManagerServiceMetrics.java, src/test/java/org/opensearch/performanceanalyzer/collectors/StatsTests.java
Related commit in Commons: https://github.com/opensearch-project/performance-analyzer-commons/commit/83cb2d427f28c9e814150d079f32be1a88b41446 
=> Add separate metric for cluster manager service events and metrics

release-notes/opensearch-performance-analyzer.release-notes-2.11.1.0.md
Add release notes for v2.11.1
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/performance-analyzer/blob/main/CONTRIBUTING.md#developer-certificate- …
=> Add release notes for v2.11.1

src/main/java/org/opensearch/performanceanalyzer/collectors/CacheConfigMetricsCollector.java
Resolves #644 
Metrics are being emitted as expected:
```
^cache_config
{"current_time":1717142304989}
{"CacheType":"field_data_cache","Cache_MaxSize":-1}
{"CacheType":"shard_request_cache","Cache_MaxSize":10737418}$
```
Tiered Caching has introduced a new ICache interface which has an OnHeap implementation which actually stores the Cache field now. We had to update the logic to how to get the cache field. Relevant PR: https://github.com/opensearch-project/OpenSearch/pull/10753
Add any other …
=> Fixed the bug in CacheConfigMetricsCollector

src/main/java/org/opensearch/performanceanalyzer/OpenSearchResources.java, src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java, src/main/java/org/opensearch/performanceanalyzer/collectors/ValueCalculator.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFDisksCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFHeapMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFThreadPoolMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java, src/main/java/org/opensearch/performanceanalyzer/config/setting/PerformanceAnalyzerClusterSettings.java, src/main/java/org/opensearch/performanceanalyzer/config/setting/handler/PerformanceAnalyzerCollectorsSettingHandler.java, src/main/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigAction.java, src/main/java/org/opensearch/performanceanalyzer/util/Utils.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/CollectorTestBase.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFDisksCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFHeapMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFThreadPoolMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/config/setting/handler/PerformanceAnalyzerCollectorsSettingHandlerTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java
=> [Backport 2.x] changes to merge PA-RTF

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java, src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java, src/main/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListener.java, src/main/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListener.java, src/main/java/org/opensearch/performanceanalyzer/transport/PerformanceAnalyzerTransportRequestHandler.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannel.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportInterceptor.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandler.java, src/main/java/org/opensearch/performanceanalyzer/util/Utils.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListenerTests.java, src/test/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListenerTests.java, src/test/java/org/opensearch/performanceanalyzer/transport/PerformanceAnalyzerTransportRequestHandlerTests.java, src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannelTests.java, src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandlerTests.java, src/test/java/org/opensearch/performanceanalyzer/util/UtilsTests.java
Adds the listener for resource utilization metrics.
1. RTFPerformanceAnalyzerSearchListener - Emits the CPU_Utilization and Heap_used metrics for task level query shard operations  (both query phase and the fetch phase).
2. RTFPerformanceAnalyzerTransportInterceptor - Emits the CPU_Utilization metric for BulkShardRequest.
Add any other …
=> Adds the listener for resource utilization metrics

src/main/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPlugin.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/config/PerformanceAnalyzerController.java, src/main/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListener.java, src/main/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListener.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannel.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportInterceptor.java, src/main/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandler.java, src/main/java/org/opensearch/performanceanalyzer/util/Utils.java, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/listener/PerformanceAnalyzerSearchListenerTests.java, src/test/java/org/opensearch/performanceanalyzer/listener/RTFPerformanceAnalyzerSearchListenerTests.java, src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportChannelTests.java, src/test/java/org/opensearch/performanceanalyzer/transport/RTFPerformanceAnalyzerTransportRequestHandlerTests.java, src/test/java/org/opensearch/performanceanalyzer/util/UtilsTests.java
porting the change #689 from the 2.x. …
=> Port pr 689

src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigActionTests.java
This commit fixes the test failiures due to regression of https://github.com/opensearch-project/OpenSearch/pull/14630/
=> fixes the UT failures caused due to Identity Service

build.gradle, src/test/java/org/opensearch/performanceanalyzer/PerformanceAnalyzerPluginTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerClusterConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerConfigActionTests.java, src/test/java/org/opensearch/performanceanalyzer/http_action/config/PerformanceAnalyzerOverridesClusterConfigActionTests.java
This PR fixes compilation issues in PA tests due to change in the constructor of the RestController in https://github.com/opensearch-project/OpenSearch/pull/15430
Resolves https://github.com/opensearch-project/performance-analyzer/issues/731 and https://github.com/opensearch-project/performance-analyzer/issues/732
=> Remove IdentityService from RestController constructor

.github/workflows/gradle.yml
This PR fixes uploads to codecov. While working on https://github.com/opensearch-project/performance-analyzer/pull/736, I noticed that uploads were hitting the rate limit and failing.
```
==> Uploading reports
url: https://codecov.io
query: branch=main&commit=c643111d76f63eadd5fe1196844f96a84df530bb&build=11[47](https://github.com/opensearch-project/performance-analyzer/actions/runs/11473403760/job/31927585948#step:9:48)3403760&build_url=https%3A%2F%2Fgithub.com%2Fopensearch-project%2Fperformance-analyzer%2Factions%2Fruns%2F11473403760&name=&tag=&slug=opensearch-project%2Fperformance-analyzer&service=github-actions&flags=&pr=&job=Java+CI&cmd_args=f
->  Pinging Codecov
https://codecov.io//upload/v4?package=bash-1.0.6&token=<hidden>&package=bash-1.0.6&token=&branch=main&commit=c643111d76f63e …
```
=> Fix test report and code coverage upload

src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFHeapMetricsCollector.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFHeapMetricsCollectorTests.java
Gauge Instrument was registering a new callback on each computation. Fixed it to be created only once for the first time.
=> Fixes the Gauge instrument to be created only once

src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollector.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFCacheConfigMetricsCollectorTests.java
Fixes the case where if RTFCacheConfigMetricsCollector got disabled once and re enabled the Gauge instruments should be recreated.
=> Fixes the re enabling of RTFCacheConfigMetricsCollector

src/main/java/org/opensearch/performanceanalyzer/action/PerformanceAnalyzerActionFilter.java, src/main/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollector.java, src/main/java/org/opensearch/performanceanalyzer/util/Utils.java, src/test/java/org/opensearch/performanceanalyzer/collectors/telemetry/RTFNodeStatsAllShardsMetricsCollectorTests.java
Skips the counter increment if value is zero and also skipping the PerformanceAnalyzerActionFilter in case of RTF mode.
=> Skips the counter increment if value is zero

build.gradle, release-notes/opensearch-performance-analyzer.release-notes-1.3.20.0.md
Fixes CVE-2024-7254 and upgrading the protobuf version to - 3.25.5
=> Fixes CVE-2024-7254

.github/workflows/delete_backport_branch.yml, .github/workflows/gradle.yml, build.gradle, gradle/wrapper/gradle-wrapper.properties, gradlew, gradlew.bat
Bump gradle to 8.14, fix backport-deletion and support JDK24
https://github.com/opensearch-project/performance-analyzer/issues/825
=> Bump gradle to 8.14, fix backport-deletion and support JDK24

build.gradle
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>### Description
Bump checkstyle and spotbug versions
=> Bump checkstyle and spotbug versions
